### ISSUE TITLE
По поводу работы

### ISSUE THREAD

**Issue by Dmitryi** [nulldef/dotfiles#1]
Здравствуйте, Алексей.
Заранее извиняюсь, что пишу в github.
Я Дмитрий. 27 августа на вашу почту отправлял вакансии Ruby on Rails dev.
Хочу узнать вы готовы рассмотреть предложение о работе?

**Comment by nulldef** [comment]
Добрый день. Не стоит писать это здесь, GitHub немного не для этого.
